import "./index.css";
import Navbar from "@/sections/header/Header";
import Footer from "@/sections/footer/Footer";
import Stairs from "@/components/Stairs/index";

export const metadata = {
  title: "Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Stairs>
          <Navbar />
          <div className="max-w-7xl lg:px-5 mx-auto">
            {children}
          </div>
          <Footer />
        </Stairs>
      </body>
    </html>
  );
}
