import "./index.css";
import Navbar from "@/sections/header/Header";
import Footer from "@/sections/footer/Footer";

export const metadata = {
  title: "Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
